import { NextResponse } from "next/server";
import type { NewsletterConfig } from "@/types";
import { delay } from "@/lib/mock";

export async function POST(request: Request) {
  const config = (await request.json()) as NewsletterConfig;
  await delay();
  const sections = config.sections
    .filter((section) => section.enabled)
    .map(
      (section) => `
        <section style="margin-bottom:24px;">
          <h2 style="font-family:Arial,sans-serif;font-size:18px;color:#111;margin-bottom:8px;">${section.title}</h2>
          <p style="font-family:Arial,sans-serif;font-size:14px;color:#555;line-height:1.6;">
            Placeholder insights for ${section.title.toLowerCase()} aligned with ${config.topic}.
          </p>
        </section>
      `
    )
    .join("\n");

  const html = `<!doctype html>
  <html>
    <body style="margin:0;padding:32px;background:#f4f5f7;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:12px;padding:32px;box-shadow:0 4px 12px rgba(15,23,42,0.1);">
        <tr>
          <td>
            <h1 style="font-size:24px;color:#111;margin-bottom:8px;">${config.topic}</h1>
            <p style="color:#555;font-size:14px;margin-bottom:24px;">Cadence: ${config.cadence} · Recipients: ${config.recipients.join(", ")}</p>
            ${sections}
            <footer style="border-top:1px solid #e5e7eb;padding-top:16px;margin-top:24px;color:#94a3b8;font-size:12px;">
              Generated by Beacon's mock AI engine.
            </footer>
          </td>
        </tr>
      </table>
    </body>
  </html>`;

  return NextResponse.json({ html });
}
