import type { AgentDefinition, AgentStep } from "@/lib/types";

const coreSteps: Record<string, AgentStep[]> = {
  standard: [
    { id: "plan", label: "Plan", description: "Frame the objective" },
    { id: "gather", label: "Gather", description: "Assemble relevant signals" },
    { id: "analyze", label: "Analyze", description: "Quantify impact" },
    { id: "recommend", label: "Recommend", description: "Surface next best actions" },
    { id: "draft", label: "Draft", description: "Package insights and outputs" }
  ],
  withCluster: [
    { id: "plan", label: "Plan", description: "Frame the market brief" },
    { id: "gather", label: "Gather", description: "Pull industry intelligence" },
    { id: "cluster", label: "Cluster", description: "Group signals and patterns" },
    { id: "recommend", label: "Recommend", description: "Prioritize plays" },
    { id: "draft", label: "Draft", description: "Assemble battlecard assets" }
  ],
  withSegment: [
    { id: "plan", label: "Plan", description: "Clarify cash goals" },
    { id: "gather", label: "Gather", description: "Pull AR ledger and payments" },
    { id: "analyze", label: "Analyze", description: "Age receivables" },
    { id: "segment", label: "Segment", description: "Group accounts by risk" },
    { id: "draft", label: "Draft", description: "Compose outreach" }
  ],
};

export const agentCatalog: AgentDefinition[] = [
  {
    id: "revenue-leakage",
    name: "Revenue Leakage",
    vertical: "quote-to-cash",
    summary: "Quantifies leakage risk across invoices and flags discount outliers.",
    headline: "Catch leakage before it hits cash flow.",
    status: "core",
    heroAction: "Run leakage scan",
    features: ["Leakage KPIs", "Invoice anomaly table", "Playbook actions"],
    steps: coreSteps.standard,
    defaultFilters: { segment: "all" },
    filters: [
      {
        id: "segment",
        label: "Segment",
        type: "select",
        options: [
          { label: "All segments", value: "all" },
          { label: "Enterprise", value: "enterprise" },
          { label: "Mid-Market", value: "mid-market" }
        ],
      },
    ],
  },
  {
    id: "l2c-analytics",
    name: "L2C Analytics",
    vertical: "operations",
    summary: "Visualizes stage throughput and identifies bottlenecks in lead-to-close.",
    headline: "Accelerate every stage of the revenue journey.",
    status: "core",
    heroAction: "Replay L2C diagnostics",
    features: ["Cycle time KPIs", "Stage duration chart", "Root-cause notes"],
    steps: coreSteps.standard,
    defaultFilters: { region: "global" },
    filters: [
      {
        id: "region",
        label: "Region",
        type: "select",
        options: [
          { label: "Global", value: "global" },
          { label: "North America", value: "NA" },
          { label: "EMEA", value: "EMEA" },
          { label: "LATAM", value: "LATAM" }
        ],
      },
    ],
  },
  {
    id: "account-hierarchy",
    name: "Account Hierarchy",
    vertical: "data",
    summary: "Builds clean household hierarchies and highlights duplicates.",
    headline: "See the full family tree for every account.",
    status: "core",
    heroAction: "Generate hierarchy",
    features: ["Hierarchy tree", "Duplicate detection", "Merge suggestions"],
    steps: coreSteps.standard,
    defaultFilters: { region: "all" },
    filters: [
      {
        id: "region",
        label: "Region",
        type: "select",
        options: [
          { label: "All", value: "all" },
          { label: "North America", value: "NA" },
          { label: "EMEA", value: "EMEA" },
          { label: "LATAM", value: "LATAM" }
        ],
      },
    ],
  },
  {
    id: "market-research",
    name: "Market Research Agent",
    vertical: "strategy",
    summary: "Synthesizes competitive, TAM, and trigger signals into a battlecard.",
    headline: "Brief the GTM org in minutes, not weeks.",
    status: "core",
    heroAction: "Assemble market brief",
    features: ["TAM projections", "Competitor highlights", "ICP fit scoring"],
    steps: coreSteps.withCluster,
    defaultFilters: { industry: "Enterprise SaaS", region: "NA" },
    filters: [
      {
        id: "industry",
        label: "Industry",
        type: "select",
        options: [
          { label: "Enterprise SaaS", value: "Enterprise SaaS" },
          { label: "Retail AI", value: "Retail AI" }
        ],
      },
      {
        id: "region",
        label: "Region",
        type: "select",
        options: [
          { label: "North America", value: "NA" },
          { label: "EMEA", value: "EMEA" },
          { label: "APAC", value: "APAC" },
          { label: "LATAM", value: "LATAM" }
        ],
      },
    ],
  },
  {
    id: "cash-collections",
    name: "Cash & Collections Copilot",
    vertical: "finance",
    summary: "Ages receivables, segments risk, and drafts outreach sequences.",
    headline: "Give every collector an AI teammate.",
    status: "core",
    heroAction: "Run AR aging",
    features: ["DSO dashboard", "Risk segmentation", "Email drafts"],
    steps: coreSteps.withSegment,
    defaultFilters: { bucket: "all" },
    filters: [
      {
        id: "bucket",
        label: "Bucket",
        type: "segmented",
        options: [
          { label: "All", value: "all" },
          { label: "0-30", value: "0-30" },
          { label: "31-60", value: "31-60" },
          { label: "61-90", value: "61-90" },
          { label: ">90", value: ">90" }
        ],
      },
    ],
  },
  // Placeholder agents
  {
    id: "lead-scoring",
    name: "Lead Scoring",
    vertical: "sales-marketing",
    summary: "Predictive scoring tuned to your funnel.",
    headline: "Lead scoring is in development.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "campaign-roi",
    name: "Campaign ROI",
    vertical: "sales-marketing",
    summary: "Measure lift and optimize spend.",
    headline: "Campaign ROI is nearly ready.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "pricing-guardrails",
    name: "Pricing Guardrails",
    vertical: "sales-marketing",
    summary: "Expose discount and approval trends.",
    headline: "Pricing guardrails launching soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "deal-desk",
    name: "Deal Desk Co-Pilot",
    vertical: "quote-to-cash",
    summary: "Automate approvals and deal packages.",
    headline: "Deal Desk is under construction.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "contract-clause",
    name: "Contract Clause Finder",
    vertical: "quote-to-cash",
    summary: "Locate risky clauses instantly.",
    headline: "Clause Finder coming soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "churn-early-warning",
    name: "Churn Early-Warning",
    vertical: "post-sales",
    summary: "Spot churn risk across CS signals.",
    headline: "Churn early-warning is on the roadmap.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "renewal-prep",
    name: "Renewal Prep",
    vertical: "post-sales",
    summary: "Brief CSMs with expansion angles.",
    headline: "Renewal prep launching soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "upsell-recommender",
    name: "Upsell Recommender",
    vertical: "post-sales",
    summary: "Identify product gaps.",
    headline: "Upsell recommender in design phase.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "margin-erosion",
    name: "Margin Erosion Detector",
    vertical: "finance",
    summary: "Track margin drift across channels.",
    headline: "Margin detector planned.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "forecast-consistency",
    name: "Forecast Consistency Checker",
    vertical: "finance",
    summary: "Compare forecast vs actuals.",
    headline: "Forecast checker is coming soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "playbook-generator",
    name: "Playbook Generator",
    vertical: "strategy",
    summary: "Spin up GTM motions by persona.",
    headline: "Playbook generator launching soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "competitive-battlecards",
    name: "Competitive Battlecards",
    vertical: "strategy",
    summary: "Compare head-to-head strengths.",
    headline: "Battlecards in development.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "data-quality",
    name: "Data Quality Sentinel",
    vertical: "data",
    summary: "Watch data drift in real time.",
    headline: "Data quality sentinel planned.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "schema-mapper",
    name: "Schema Mapper",
    vertical: "data",
    summary: "Translate objects across systems.",
    headline: "Schema mapper coming soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "kpi-harmonizer",
    name: "KPI Harmonizer",
    vertical: "data",
    summary: "Align metrics definitions.",
    headline: "KPI harmonizer in discovery.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "process-bottleneck",
    name: "Process Bottleneck Finder",
    vertical: "operations",
    summary: "Find blockers across workflows.",
    headline: "Process bottleneck finder coming soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "playbook-executor",
    name: "Playbook Executor",
    vertical: "operations",
    summary: "Automate cross-team actions.",
    headline: "Playbook executor in planning.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "capacity-planner",
    name: "Capacity Planner",
    vertical: "operations",
    summary: "Right-size headcount vs demand.",
    headline: "Capacity planner launching soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "onboarding-copilot",
    name: "Onboarding Copilot",
    vertical: "people",
    summary: "Automate onboarding journeys.",
    headline: "Onboarding copilot in build.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "skills-matrix",
    name: "Skills Matrix Builder",
    vertical: "people",
    summary: "Map team capabilities vs needs.",
    headline: "Skills matrix builder planned.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
  {
    id: "pulse-synthesizer",
    name: "Pulse Synthesizer",
    vertical: "people",
    summary: "Summarize surveys and signals.",
    headline: "Pulse synthesizer coming soon.",
    status: "coming-soon",
    heroAction: "Coming soon",
    features: [],
    steps: coreSteps.standard,
  },
];

export const verticalLabels: Record<AgentDefinition["vertical"], string> = {
  "sales-marketing": "Sales & Marketing",
  "quote-to-cash": "Quote-to-Cash",
  "post-sales": "Post-Sales",
  finance: "Finance",
  strategy: "Strategy",
  data: "Data",
  operations: "Operations",
  people: "People",
};

export function getAgentById(agentId: string) {
  return agentCatalog.find((agent) => agent.id === agentId);
}
